GET http://localhost:3030/booking-slot/user-details/
###

POST http://localhost:3030/booking-slot/create/
Content-Type: application/json
Accept: application/json

{
    "id": "6",
    "name": "Krishna",
    "mobileNumber": "8015298157",
    "email": "krishna3@gmail.com",
    "date": "02-07-2023 Sun",
    "time": "11:15 - 12:15"
}
